/*
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.tests

import com.btc.serviceidl.idl.IDLSpecification
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(IdlInjectorProvider)
class IdlParsingTest {
	@Inject
	ParseHelper<IDLSpecification> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			module Test {}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
