/*
 * generated by Xtext
 */
package com.btc.cab.servicecomm.prodigd;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IdlRuntimeModule extends com.btc.cab.servicecomm.prodigd.AbstractIdlRuntimeModule {

}
