/*
 * generated by Xtext
 */
package com.btc.cab.servicecomm.prodigd;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class IdlStandaloneSetup extends IdlStandaloneSetupGenerated{

   public static void doSetup() {
      new IdlStandaloneSetup().createInjectorAndDoEMFRegistration();
   }
}

