/*
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IdlRuntimeModule extends AbstractIdlRuntimeModule {
}
