/*
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IdlStandaloneSetup extends IdlStandaloneSetupGenerated
{

    static def void doSetup()
    {
        new IdlStandaloneSetup().createInjectorAndDoEMFRegistration()
    }
}
