/*********************************************************************
* \author see AUTHORS file
* \copyright 2015-2018 BTC Business Technology Consulting AG and others
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
**********************************************************************/
/**
 * \file       IdlUiModule.java
 * 
 * \brief      Use this class to register components to be used within the IDE
 * 
 * \remark     Generated by Xtext
 */

package com.btc.cab.servicecomm.prodigd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * .
 */
public class IdlUiModule extends com.btc.cab.servicecomm.prodigd.ui.AbstractIdlUiModule
{
   
   public IdlUiModule(AbstractUIPlugin plugin)
   {
      super(plugin);
   }
   
   public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration ()
   {
      return IdlHighlightingConfiguration.class;
   }
   
   public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator()
   {
      return IdlSemanticHighlightingCalculator.class;
   }
}
